### ISSUE TITLE
Resize relative to the container, not the viewport

### ISSUE THREAD

**Issue by scottybo** [twbs/rfs#117]
I was wondering if it's possible to have responsive text that fits to the size of the container instead of the width/height of the viewport.

My users are allowed to add/delete text to a div via a form input. I'd like the text to resize to fit the available space as they type (so basically, as they type more, the font size gets smaller).

**Comment by MartijnCuppens** [comment]
Hi @scottybo

I guess this is currently not possible with CSS. The percentage in font sizes is relative to the font size of the parent, not the container width.

The only way you can size the font sizes based on the available space is using iframes.
