### ISSUE TITLE
Base font size as a parameter

### ISSUE THREAD

**Issue by einarsrud** [twbs/rfs#148]
I'm sure there's a good reason to why the base font size is set as a global variable, but could it be an idea to let it be overridden by adding it as a parameter to the function call?

`@mixin rfs($fs, $fs-min: $rfs-base-font-size, $important: false)`

The typography is sometimes, in my opinion, scaled down too much when working with a mix of large and small font sizes.

**Comment by MartijnCuppens** [comment]
The purpose of RFS is to rescale all sizes without having to worry about cross sizing (for example a `h3` which becomes larger than a `h2`), which this option could introduce.

You can decrease the `$rfs-factor` if you want to decrease the effect of the rescaling.
