### ISSUE TITLE
JisonLexerError: Lexical error on line 1: Unrecognized text - Erroneous area

### ISSUE THREAD

**Issue by seth100** [twbs/rfs#176]
Hi,

I don't know whether this issue is related to `rfs` itself, but it happened after upgrading to `v9.0.1` recently.
I opened the complete issue on the `postcss-calc` repo, see [here](https://github.com/postcss/postcss-calc/issues/99).

Thank you!

**Comment by MartijnCuppens** [comment]
Hi @seth100,

- What version did you upgrade from?
- What post/preprocessor are you using (less/sass/PostCSS/Stylus)? 
  - If it's Sass, what compiler are you using? LibSass or Dart Sass?

**Comment by seth100** [comment]
> Hi @seth100,
> 
>     * What version did you upgrade from?
From `v9.0.0`

>     * What post/preprocessor are you using (less/sass/PostCSS/Stylus)?
>         * If it's Sass, what compiler are you using? LibSass or Dart Sass?
I'm not sure, I use [this](https://nuxtjs.org/faq/postcss-plugins/) from `nuxt.js`
