### ISSUE TITLE
RFS doesn't work

### ISSUE THREAD

**Issue by VladimirMikulic** [twbs/rfs#178]
Hi,

I've installed your library and tried to refactor one of my projects to see how it performs.
What I've found really strange is that font-size jumps from 48px(viewport wider than 1200px) to 24px (viewport on 1199px and below).

Shouldn't it fluidly resize?

Thanks.

**Comment by MartijnCuppens** [comment]
> Shouldn't it fluidly resize?

Yes, it should.

Have you changed the font size of `html`? This will change the value of `rem`, causing such behaviour.

**Comment by VladimirMikulic** [comment]
> Have you changed the font size of html? This will change the value of rem, causing such behaviour.

No, I did not.

**Comment by MartijnCuppens** [comment]
Could you check if the font size also jumps on this demo: https://project-rfs.github.io/docs/4.3/content/typography/#display-headings

**Comment by VladimirMikulic** [comment]
The demo is fine. It resizes properly.

**Comment by MartijnCuppens** [comment]
Could you provide a demo or some input/output examples with the incorrect behaviour?

**Comment by VladimirMikulic** [comment]
Here it is: https://streamable.com/274qr

**Comment by MartijnCuppens** [comment]
It looks like you're applying some css to center the text, some additional font size properties might also be applied too? It's quite hard to see that without any code I can debug.

**Comment by VladimirMikulic** [comment]
I've found the issue...
![Screenshot_20191023_212717](https://user-images.githubusercontent.com/35997844/67427267-14acf400-f5dc-11e9-8215-f9713639a992.png)

There is no plus sign between 1.425rem and 2.1vw.
When I add it manually in DevTools RFS works.

RFS is installed via NPM version 9.0.1.

**Comment by VladimirMikulic** [comment]
Well, I resolved the issue. After a few uninstalls of RFS package, I noticed that the node_modules folder was damaged.
