### ISSUE TITLE
Using rfs 9 with Bootstrap 4.3.1

### ISSUE THREAD

**Issue by dangelion** [twbs/rfs#185]
Hi
I'm working on a project that uses Bootstrap 4.3.1 which includes rfs 8 (as I understood) but I need to use rfs 9. Actually I have strange problems, caused (I think) by a conflict between rfs 8 and 9. Is it possible?

Here what I've done and the wrong result.

I installed rfs 9 with:
`npm install rfs` => in `package.json` `"rfs": "^9.0.2"`

Then I import it in my **app.scss**
```
@import "common/variables";

// Bootstrap
@import '~bootstrap/scss/bootstrap';

// RFS (Responsive Font Size)
@import "~rfs/scss";

... all the other partials
```
In **_variables.scss** I set:
```
// Enable RFS
$enable-responsive-font-sizes: true;
```
and finally use it, like this:
```
.heading4 {
  @include font-size(40px);
  @include margin-bottom(20px);
}
```
The CCS result is:

[![rfs.jpg](https://i.postimg.cc/13FWHVSn/rfs.jpg)](https://postimg.cc/tsXtRTYp)

Why the first calc() font-size is overriden by the `font-size: 1.25rem !important`?
Why there is this `font-size: 1.25rem !important`?
Why there isn't the `margin-bottom` property?

Please someone can helps?
Thanks

**Comment by MartijnCuppens** [comment]
The way you described you configured it should work. I tested with
```
$enable-responsive-font-sizes: true;
@import "../node_modules/bootstrap/scss/bootstrap";
@import "../node_modules/rfs/scss";

.heading4 {
  @include font-size(40px);
  @include margin-bottom(20px);
}
```
And got:

```
// Bootstrap CSS with RFS enabled here

// and then:

.heading4 {
  font-size: calc(1.375rem + 1.5vw);
  margin-bottom: 1.25rem;
}

@media (min-width: 1200px) {
  .heading4 {
    font-size: 2.5rem;
  }
}
```
