### ISSUE TITLE
Wrong calculation for baseValue with rem units

### ISSUE THREAD

**Issue by aggreggator** [twbs/rfs#193]
First thank you for this great lib!

I think at line 30 multiplication should be used instead of division.
https://github.com/twbs/rfs/blob/bbdd5597d81af2a0424d27133510143dbb47efa5/lib/rfs.js#L29-L31

**Comment by MartijnCuppens** [comment]
@aggreggator,

The `baseValue` is used to convert the px values to `rem` and this should work as expected. See https://codepen.io/MartijnCuppens/pen/wvadXRb?editors=1100.
