### ISSUE TITLE
font-size mixing not working inisde for loop

### ISSUE THREAD

**Issue by gkorakas-eli** [twbs/rfs#211]
I am using bootstrap and I have enabled the rfs. 
With a simple loop I add some classes that handle the font size:

```
@for $i from 10 through 30 {
    .fs-#{$i} {
        @include font-size("#{$i/10}rem");
    }
}
```

Please for your advice.

**Comment by MartijnCuppens** [comment]
`"#{$i/10}rem"` is parsed as a string, you can change this to:

```scss
@for $i from 10 through 30 {
    .fs-#{$i} {
        @include font-size($i * .1rem);
    }
}
``` 

https://codepen.io/MartijnCuppens/pen/MWwwbow
