### ISSUE TITLE
SCSS variable support?

### ISSUE THREAD

**Issue by evandiamond** [twbs/rfs#218]
@MartijnCuppens Hi there.

First of all, wanted to start out by saying, thank you for creating such a kick-ass plugin to support the future of Web development.

I'm using `bootstrap@^4.4.1` and was trying to use SCSS variables within the mixin, but was running into issues. I tried upgrading to `"rfs": "^9.0.2"` and it seems there are similar issues related to the SCSS variables.

My Variables:
```
$font-size: 1rem;
$base-font-size: $font-size;
```

Code I am trying to use :

*Option 1*
```
body {
  @include rfs(#{$base-font-size});
}
```

or 

*Option 2*
```
body {
  @include rfs($base-font-size);
}
```

or 

*Option 3*
```
body {
  @include rfs(30px);
}
```

When I change the `rfs-breakpoint` variable to `$rfs-breakpoint: 992px;`, I get the following error:
```
 Module build failed: 
              $variable-width: #{$value-diff * 100 / $rfs-breakpoint}#{$variable-unit};
                                ^
          0.90726/px isn't a valid CSS value.
```

If I remove my `$rfs-breakpoint` override variable, everything compiles, but *only* if I use *Option 3* above.

I've tried messing around with the `$rfs-font-size-unit: rem;` but that doesn't seem to do anything either.

Am I doing something wrong or is this not supported yet?

**Comment by MartijnCuppens** [comment]
Thanks @evandiamond!

Keep in mind Bootstrap 4 uses RFS 8 and the mixin is included in the bootstrap source code by default. If you're going to include as well rfs 8 and 9, you will end up with issues.

From the info you provided, I can't really help you any further. I guess you configured rfs somehow wrong, but I need more details or a demo to see what's wrong.

**Comment by evandiamond** [comment]
@MartijnCuppens 
Does RFS 8 by default work with SCSS variables inside the mixin? Because I couldn't get that to work either.

**Comment by MartijnCuppens** [comment]
Sure, Bootstrap works that way.

**Comment by evandiamond** [comment]
Right, that's what I figured. So, a little more sleuthing brings me to these points:

1. Overriding the breakpoint only works, if you leave off the unit.
```
$enable-responsive-font-sizes: true;
$rfs-breakpoint: 992;
```

2. SCSS variables work, as long as your font-size is in `px` for some reason. If you use `rem` it will not output anything.
```
$base-font: 16px;
@include font-size($base-font);
```

If you use `$base-font: 1rem;` it will not work, even if meddle with this `$rfs-font-size-unit: rem;`.

Can you confirm on your end?

**Comment by MartijnCuppens** [comment]
Nope, all variables in Bootstrap are set in `rem`. You can also test things with https://github.com/twbs/rfs/blob/master/examples/scss/src/main.scss (clone project, run `npm install` and execute `node index.js` in `examples/scss`).
