### ISSUE TITLE
fallback values for missing calc() browser support

### ISSUE THREAD

**Issue by benjaminpreiss** [twbs/rfs#222]
I would like to suggest adding fallback values in case the browser doesnt support calc().

This could be easily done by adding the fallback value at the beginning of the generated css file.

**Comment by MartijnCuppens** [comment]
This should be achievable by switching to the `max-media-query` mode:
https://github.com/twbs/rfs/blob/master/scss.scss#L37-L38

**Comment by benjaminpreiss** [comment]
Sure but I was thinking of a out of the box solution which doesn't require thinking :)

**Comment by MartijnCuppens** [comment]
Ok, fine by be. Feel free to open a PR for this.

**Comment by benjaminpreiss** [comment]
perfect! thank you

**Comment by benjaminpreiss** [comment]
so here is my idea:

in the generated css file every

`calc(1.15625rem + 1.125vw)`

should have a fallback value defined before. for example:

```
font-size: 2rem;
font-size: calc(1.15625rem + 1.125vw);
```

therefore any browser that doesn't support calc() will only render the first declaration.
a browser that does support calc() will only render the second declaration.
@MartijnCuppens what do you think?

**Comment by MartijnCuppens** [comment]
Gonna pass on this for now, switching to `max-media-query` mode will give users the fallback they need.
