### ISSUE TITLE
$rfs-two-dimensional: true wrong media queries?

### ISSUE THREAD

**Issue by benjaminpreiss** [twbs/rfs#223]
at the moment the media queries for two dimensional mode are generated to look like this:

`@media (min-width: 1200px), (min-height: 1200px) {`

I think this leads to undesired behavior for screens with very high or very low aspect ratio.

better would be to change this to:

`@media (min-width: 1200px) and (min-height: 1200px) {`

**Comment by MartijnCuppens** [comment]
Yup, correct. This should be a `,` in `min-media-query` mode and `and` in `max-media-query` mode.

Do you want to make a PR for this or shall I have a look?

**Comment by benjaminpreiss** [comment]
hmm... I think it should be `and` for both!

But that depends on how we understand the modes `min-media-query` and `max-media-query`.
The way I understand them:
1. `min-media-query`: `font-size(...)` defines the maximum font-size, when (height > 1200px) || (width > 1200px)
2. `max-media-query`: `font-size(...)` defines the minimum font-size, when (height < 1200px) || (width < 1200px)

that means that it should be `and` for `min-media-query` and `max-media-query`.

**Comment by benjaminpreiss** [comment]
I just tested `min-media-query` with `and`. I think it works like a charm.

**Comment by MartijnCuppens** [comment]
Yup, it's the other way around indeed. Go ahead!

**Comment by benjaminpreiss** [comment]
okay, these are the files that I changed:
1. lib/rfs.js
2. less.less
3. scss.scss
4. stylus.styl

did i forget any files?

**Comment by MartijnCuppens** [comment]
I don't think so, you might need to adjust the test files too. Run `npm test` to check if everything is ok.

**Comment by benjaminpreiss** [comment]
okey, I adjusted the tests as well. I realized that there are test missing now, specifically:

1. test8 but with `$rfs-mode: max-media-query`
2. test9 but with `$rfs-mode: max-media-query`
3. test10 but with `$rfs-mode: max-media-query`
4. test11 but with `$rfs-two-dimensional: true`

I must admit I have a lot to do at the moment, thats why I would be glad if you could do it :/
