### ISSUE TITLE
how to use rfs-fluid-value($value) and rfs-value($value)

### ISSUE THREAD

**Issue by dkebler** [twbs/rfs#232]
I encountered a use case where I need to set a height of a group of elements
they change in response to what rfs calculates for a font size on one of them.

So far I've only been using the mixin but now I'd like to get the actual value.

So I discovered that there are these two functions undocumented that appear to calculate the value that then gets used in the mixin.

1.  Which one should I use?
2.  I can't seem to get the return value set to a variable and then use it.
3.  Is it a good idea to use rfs on padding (i.e. visually as font sizes change should the padding also scale) ? 

would like to do this?
```
$rfs-base-font-size = 1rem
$item-font-factor = 1.3
$new-font-size = rfs-value($rfs-base-font-size * $item-font-factor)
$common-height = $new-font-size + $some-padding
```

Can you give insight and/or document the use of these two? in my use case?

**Comment by MartijnCuppens** [comment]
In your case I think it would be better to set the height in `em` (relative to the font size)
