### ISSUE TITLE
PostCss 

### ISSUE THREAD

**Issue by merijnponzo** [twbs/rfs#261]
Hello,

How/where would i add a PostCSS: baseValue to set the minimum fontsize to like 14px

I'm using vuejs, with vue.config.js
and within postcss.config.js
```
module.exports = {
  plugins: [
    require('rfs'),
    require('autoprefixer')
  ]
}
```
Thank you!

**Comment by MartijnCuppens** [comment]
This should do the trick:
```js
module.exports = {
  plugins: [
    require('rfs')({baseValue: 10}),
    require('autoprefixer')
  ]
}
```
