### ISSUE TITLE
Introduce my plugin in README(If you think it is good)

### ISSUE THREAD

**Issue by winston0410** [twbs/rfs#287]
Hi, I really love rfs and I am now using it in my workflow.  However, writing `rfs()` everywhere is really a pain in the ass, thus I have written a PostCSS plugin to automatically apply `rfs()` for users.  Users can include or exclude this transformation by prop, values and selectors.

https://github.com/winston0410/postcss-rfs-autopilot

https://www.npmjs.com/package/postcss-rfs-autopilot

Any feedback is appreciated! If you think my work is a good one, I hope you can add it to the readme of RFS, so that more people can know about it and avoid this chore.  Thank you!

**Comment by MartijnCuppens** [comment]
Looks nice indeed! 💪

> I hope you can add it to the readme of RFS, so that more people can know about it and avoid this chore

I'm gonna pass on this and keep the repo only for the main project.
