### ISSUE TITLE
Is Bootstrap RFS and RFS engine same ?

### ISSUE THREAD

**Issue by yushanwebdev** [twbs/rfs#309]
Is RFS in the Bootstrap framework and RFS engine itself the same in every way ? because I have found a difference in **Base Value** configuration.

- In Bootstrap = $rfs-base-font-size
- In Engine = $rfs-base-value

**Comment by MartijnCuppens** [comment]
Bootstrap 4 uses RFS v8, which only supports fluid rescaling for font sizes. Bootstrap 5 will use RFS v9, which supports fluid rescaling for all properties, hence its change in variables.

Docs of RFS v8 are available here: https://github.com/twbs/rfs/tree/v8.0.4

**Comment by yushanwebdev** [comment]
Thanks @MartijnCuppens
