### ISSUE TITLE
Error while running less - Potentially unhandled rejection [2] Could not parse call arguments or missing ')' on line 120

### ISSUE THREAD

**Issue by riteshrk1** [twbs/rfs#312]
I installed the rfs with bower install rfs --save 
and run the gulp less to build the project but face the below issue.

Potentially unhandled rejection [2] Could not parse call arguments or missing ')' in file C:\Products\test\dev\bower_components\rfs\less.less line no. 120

My first thought that i might be some issue in my project but than i tested it on https://lesstester.com/ it throws the same error if I comment line no 120 than it goes to no 187 and than 192. 

Can you help me with this.

**Comment by MartijnCuppens** [comment]
You're using an outdated version of less. If you upgrade to less 3.6 or later (I would recommend the latest version, 3.8), this issue should be fixed. You can also test this with lesstester.com.

**Comment by riteshrk1** [comment]
Thanks @MartijnCuppens , Yes its not working on lower version. is there any other way for lower version?

**Comment by MartijnCuppens** [comment]
We could rewrite the less file, but updating your dependencies would definitely be the best option. `npm install less@3.13.0` should do the trick.

**Comment by riteshrk1** [comment]
Thanks for your help @MartijnCuppens , But I was looking for the global solution as my other components are compatible with my angular 1.2.

**Comment by MartijnCuppens** [comment]
less 3.6 is almost 3 years old now, I don't have any plans to support packages that are older than that.
