### ISSUE TITLE
PostCSS 8 compatibility

### ISSUE THREAD

**Issue by SimonDesautels** [twbs/rfs#344]
My `rfs` package is at version 9.0.3. 

I updated PostCSS to version 8 and this is the error I am getting : 

```
postcss-rfs: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
```
I guess it's referring to this  :
https://github.com/twbs/rfs/blob/1a22aa714f20c4268b722319b2b83c0067d290e3/postcss.js#L17

Is it planned to support PostCSS 8 in the near future?

**Comment by sebastianbaumann** [comment]
+1

"rfs": "^9.0.3" + "postcss": "^8.2.8" =>    postcss-rfs: postcss.plugin was deprecated.

**Comment by stefanoverna** [comment]
This is not just a simple warning, but the package itself is broken with PostCSS v8, and outputs weird CSS rules, especially if using `postcss-nested` together with it.
