### ISSUE TITLE
RFS + Less + css variables warning

### ISSUE THREAD

**Issue by salunet** [twbs/rfs#368]
i use RFS in combination with Less and css variables.

.rfs(1rem, --fontsize);

When i compile it with codekit, do math operations set to always, i got a warning:
- Compiled successfully, but with warnings: --math=always is deprecated and will be removed in the future.

When i compile it with codekit, do math operations set to always, expect division parentheses, i got a warning:
- Compiling failed with this error: SyntaxError: Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?

It probably won't go well in the future. Hope someone can find a solution to fix this.

**Comment by MartijnCuppens** [comment]
What version of less are you using?

**Comment by sanderTalmark** [comment]
I write my less in Atom and than i compile it with Codekit. Codekit uses version 4.1.1 of less. But i don't think this is the issue.

What i try to do is to combine css variable with rfs.

Normaly i would do something like:

:root {
--smallfontsize:   5rem;
--largefontsize:   10rem;
}

But what i want is this:

:root {
.rfs(5rem, --smallfontsize);
.rfs(10rem, --largefontsize);
}

And this create the error from above.

**Comment by MartijnCuppens** [comment]
Yup, RFS seems to be broken in `v4`, caused by this bug upstream: https://github.com/less/less.js/issues/3615
