### ISSUE TITLE
Variation in size range seems too small

### ISSUE THREAD

**Issue by David263** [twbs/rfs#376]
The variation in apparent font-size between very narrow viewports and very wide viewports seems rather small to me. On my websites, I would like to use a larger range. Is there a way I can achieve this using Bootstrap 5 with just HTML and/or custom CSS? I don't want to rebuild the standard Bootstrap 5 library. I consider a larger change in size to be very much in the spirit of responsive design. Some text blocks that currently cause a horizontal scrollbar to be needed on mobile devices could instead be displayed automatically in smaller text, with no horizontal scrollbar, as compared with laptops/desktops.

**Comment by MartijnCuppens** [comment]
Hi @David263,

RFS is a unit resizing engine which can be completely configured to your needs with either Sass, Less, PostCSS or Stylus. It's not possible to do any customizations in CSS because these tools generate the CSS.
