### ISSUE TITLE
Minimum font size.

### ISSUE THREAD

**Issue by digital-inception** [twbs/rfs#436]
How do I set a minimum font size?
E.g h1 max font size must be 50px. This is easy to do. 
But I cant find a way to set h1 minimum font size to 40px.

I also can't set multiple breakpoints to try and override this.

**Comment by kumarsanu2002** [comment]
hey, you can use Cal() function:-
h1{
  font-size: calc(4vw + 4vh + 2vmin);
}

If it is helpful let me know.

**Comment by MartijnCuppens** [comment]
You don't need to set a minimum size, the whole idea of RFS is to automatically calculate how it rescales. Have a look at https://css-tricks.com/using-a-mixin-to-take-the-math-out-of-responsive-font-sizes/, so you can find out how it works.
