### ISSUE TITLE
Version 7.1.8 Post-Install Issue

### ISSUE THREAD

**Issue by themounthead** [twbs/rfs#44]
I've been using the rfs *v 7.1.4* since the last 2 months without a problem. I recently started a new Project and did a `npm install` followed by the project execution.

I noticed the below error: 
`ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed: 
        @error "`#{$rfs-breakpoint-unit}` is not a valid unit for $rfs-breakpoint-unit. Use `px`, `em` or `rem`.";
       ^
      `` is not a valid unit for $rfs-breakpoint-unit. Use `px`, `em` or `rem`. `

I reviewed the documentation to check for any breaking changes or whether I had to explicitly specify the **rfs-breakpoint-unit**  (and I tried doing that) but it didn't work.

On a bit of investigation, I could see that there has been a new version upgrade to *v7.1.8*.

I then reverted to the previous version with `npm install rfs@7.1.4 --save` and things worked as expected -- no error. (I do see a difference in the packages between 7.1.4 and 7.1.8)

Am I missing something in the new release ? Please advise.

**Comment by MartijnCuppens** [comment]
Hi @themounthead,

Do you override the `unit()` function somewhere in your setup?

**Comment by themounthead** [comment]
Thanks for your response. 

I've left the RFS defaults *as is*, haven't done any overrides or variable changes. Oddly the same setup works fine with v7.1.4. 

Is there any new configuration or preset needed ?  Thanks.

**Comment by MartijnCuppens** [comment]
There is no different configuration needed to upgrade from 7.1.4 to 7.1.8. Can you test the versions between 7.1.4 and 7.1.8 so we can detect where it went wrong?

**Comment by MartijnCuppens** [comment]
@themounthead,  could it be you 're including the mixin twice? I encountered the same error today when I did this.

**Comment by MartijnCuppens** [comment]
Can you try `v7.1.9` and let me know if everything is ok with that version?

**Comment by themounthead** [comment]
@MartijnCuppens , I tried out the new version and as you mentioned I see a Warning stating that the 'RFS is included more than once'. This kind of puts me in a fix. 

I've organized my App into components with each component having its own *.scss* properties. At the global level, I've defined a variables file where I've specified all Sass variables and imported RFS here. 

If I move the RFS import at the Application root, I get an error `no mixin named rfs` which implies that the mixin is needed at every `@include`.

Am I missing something, please advise.

**Comment by themounthead** [comment]
@MartijnCuppens ,  please bear with me a bit longer. I'm kind of going in circles here.

I've been able to import other mixins like `_typi`, `_include-media` globally without any error/warning. 

My doubt is when I import RFS once (at the root scope), I get an error `no mixin named rfs` from every module component that uses the `@include rfs` mixin.  
This error led me to include it within my .scss variables file. But on doing that, I end up with a long stream of warnings that I shouldn't include it more than once (which I agree is not a good practice).

Does this mean I have to define the RFS variables in **only one file** and refer them in other .scss component files. 

Thanks

**Comment by themounthead** [comment]
@MartijnCuppens , this appears to be a problem with my webpack configuration and not RFS. Thanks for introducing the warning, it definitely helped me trace the source. 

I'll try to resolve it from here.
