### ISSUE TITLE
How to it this with tailwind ?

### ISSUE THREAD

**Issue by issam-seghir** [twbs/rfs#457]
How to it this with tailwind ?

**Comment by Alex-Toucan** [comment]
Bootstrap is better, Bootstrap is king 👑

**Comment by Issam-seghir** [comment]
> Bootstrap is better, Bootstrap is king 👑
While I respect your perspective, it seems we might have veered off-topic here. 
My inquiry was specifically about Tailwind CSS, and I'm eager to explore solutions within that framework. If you have insights on how to achieve my goal using Tailwind, I'm all ears! Comparing frameworks is a kid's game – both have their strengths, The crown doesn't fit everyone's head, and different projects may demand different frameworks.

**Comment by Huixh111** [comment]
1

**Comment by Huixh111** [comment]
pp

**Comment by MartijnCuppens** [comment]
It's available as a Tailwind plugin here: https://github.com/MartijnCuppens/tailwind-fluid.

**Comment by issam-seghir** [comment]
> It's available as a Tailwind plugin here: https://github.com/MartijnCuppens/tailwind-fluid.
thanks, i found out that I can use it with postcss and Tailwind it's just a postcss plugin so they work Harmoniously

**Comment by issam-seghir** [comment]
> It's available as a Tailwind plugin here: https://github.com/MartijnCuppens/tailwind-fluid.
thanks, i found out that I can use it with postcss and Tailwind its just a postcss plugin so they work Harmoniously
