### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/rfs#82]
Have a look at linting the CSS and JS and add appropriate scripts.

- [x] Use `xo` for js linting
- [ ] Use `stylelint` for CSS linting

**Comment by XhmikosR** [comment]
Note that for JS, I'd say just go with `xo`. Should give us a pretty good result with minimum setup. I can set it up later if you agree.

**Comment by MartijnCuppens** [comment]
Fine by me, I'll have a look at the CSS part than.
